apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - chat_in
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
