apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: chat-in-trigger
spec:
  broker: default
  filter:
    attributes:
      type: chat
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: explicit-filter
    uri: /filter
