apiVersion: v1
kind: Service
metadata:
  name: {{ include "flights.fullname" . }}
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    {{- include "flights.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flights.selectorLabels" . | nindent 4 }}
