apiVersion: gateway-operator.konghq.com/v1beta1
kind: DataPlane
metadata:
  name: dataplane-example
  namespace: kong
spec:
  deployment:
    rollout:
      strategy:
        blueGreen:
          promotion:
            strategy: BreakBeforePromotion
    podTemplateSpec:
      spec:
        containers:
          - name: proxy
            image: kong/kong-gateway-dev:3.5
            env:
              - name: KONG_ROLE
                value: data_plane
              - name: KONG_DATABASE
                value: "off"
              - name: KONG_CLUSTER_MTLS
                value: pki
              - name: KONG_CLUSTER_CONTROL_PLANE
                value: 8efd4ea275.us.cp0.konghq.com:443
              - name: KONG_CLUSTER_SERVER_NAME
                value: 8efd4ea275.us.cp0.konghq.com
              - name: KONG_CLUSTER_TELEMETRY_ENDPOINT
                value: 8efd4ea275.us.tp0.konghq.com:443
              - name: KONG_CLUSTER_TELEMETRY_SERVER_NAME
                value: 8efd4ea275.us.tp0.konghq.com
              - name: KONG_CLUSTER_CERT
                value: /etc/secrets/kong-cluster-cert/tls.crt
              - name: KONG_CLUSTER_CERT_KEY
                value: /etc/secrets/kong-cluster-cert/tls.key
              - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
                value: system
              - name: KONG_KONNECT_MODE
                value: "on"
              - name: KONG_VITALS
                value: "off"
            volumeMounts:
              - name: cluster-certificate
                mountPath: /var/cluster-certificate
              - name: kong-cluster-cert
                mountPath: /etc/secrets/kong-cluster-cert/
                readOnly: true
        volumes:
          - name: cluster-certificate
          - name: kong-cluster-cert
            secret:
              secretName: kong-cluster-cert
              defaultMode: 420