apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-bot-detection
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  deny:
    - kong-builders
    - kongcast
    - instagram
plugin: bot-detection
