apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-proxy-cache
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  response_code:
    - 200
  request_method:
    - GET
    - HEAD
  content_type:
    - text/plain
    - application/json
  cache_ttl: 60
  strategy: memory
plugin: proxy-cache
