# -----------------------------------------------------------------------------
# Admin Service
# -----------------------------------------------------------------------------
admin:
  # https://github.com/Kong/charts/blob/master/charts/kong/README.md#prometheus-operator-integration
  labels:
    enable-metrics: "true"
  tls:
    parameters: [ ]

# enable metrics collection
podAnnotations:
  prometheus.io/scrape: "true" # Ask Prometheus to scrape the
  prometheus.io/port: "8100"   # Kong pods for metrics

#proxy:
#  stream:
#    # Set the container (internal) and service (external) ports for this listen.
#    # These values should normally be the same. If your environment requires they
#    # differ, note that Kong will match routes based on the containerPort only.
#    - containerPort: 9000
#      servicePort: 9000
#      protocol: TCP
#      # Optionally set a static nodePort if the service type is NodePort
#      # nodePort: 32080
#      # Additional listen parameters, e.g. "ssl", "reuseport", "backlog=16384"
#      # "ssl" is required for SNI-based routes. It is not supported on versions <2.0
#  #   parameters: []
#
## -----------------------------------------------------------------------------
## UDP Proxy
## -----------------------------------------------------------------------------
#udpProxy:
#  # Enable creating a Kubernetes service for UDP proxying
#  enabled: true
#  type: LoadBalancer
#
#  stream:
#    - containerPort: 9999
#      servicePort: 9999
#      protocol: UDP
#  parameters: [ "reuseport" ]
