# -----------------------------------------------------------------------------
# Admin Service
# -----------------------------------------------------------------------------
admin:
  # https://github.com/Kong/charts/blob/master/charts/kong/README.md#prometheus-operator-integration
  labels:
    enable-metrics: "true"

# -----------------------------------------------------------------------------
# UDP Proxy
# -----------------------------------------------------------------------------
udpProxy:
  # Enable creating a Kubernetes service for UDP proxying
  enabled: true
  type: LoadBalancer

  stream:
    - containerPort: 9999
      servicePort: 9999
      protocol: UDP
  parameters: [ "reuseport" ]

# -----------------------------------------------------------------------------
# Ingress Controller parameters
# -----------------------------------------------------------------------------
ingressController:
  image:
    repository: kong/kubernetes-ingress-controller
    tag: "2.0.3"
  # Specify individual namespaces to watch for ingress configuration. By default,
  # when no namespaces are set, the controller watches all namespaces and uses a
  # ClusterRole to grant access to Kubernetes resources. When you list specific
  # namespaces, the controller will watch those namespaces only and will create
  # namespaced-scoped Roles for each of them. Note that watching specific namespaces
  # disables KongClusterPlugin usage, as KongClusterPlugins only exist as cluster resources.
  # Requires controller 2.0.0 or newer.
  watchNamespaces: [ "udpingress-example" ]

# Annotation to be added to Kong pods
# required for Kong Prometheus 
podAnnotations:
  prometheus.io/scrape: "true" # Ask Prometheus to scrape the
  prometheus.io/port: "8100"


serviceMonitor:
  # Specifies whether ServiceMonitor for Prometheus operator should be created
  # If you wish to gather metrics from a Kong instance with the proxy disabled (such as a hybrid control plane), see:
  # https://github.com/Kong/charts/blob/main/charts/kong/README.md#prometheus-operator-integration
  enabled: true
  labels:
    # prometheus stack release name
    release: promstack