apiVersion: v1
kind: Service
metadata:
  name: backend-v0
  namespace: kuma-demo
spec:
  selector:
    app: kuma-demo-backend
    version: v0
  ports:
    - name: api
      port: 3001
      appProtocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend-v1
  namespace: kuma-demo
spec:
  selector:
    app: kuma-demo-backend
    version: v1
  ports:
    - name: api
      port: 3001
      appProtocol: http
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: enable-sales-backend
  namespace: kuma-demo
spec:
  parentRefs:
    - name: backend
      namespace: kuma-demo
      port: 3001
      kind: Service
  rules:
    - backendRefs:
        - name: backend-v0
          port: 3001
          weight: 1
        - name: backend-v1
          port: 3001
          weight: 0
