version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
      MYSQL_DATABASE: summit
      MYSQL_USER: summit
      MYSQL_PASSWORD: summit

  app:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    restart: always
volumes:
  db_data: {}
