version: "3.9"

networks:
  default:
    name: kong-net

services:
  kong:
    image: kong:2.8
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/config.yaml'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_LOG_LEVEL: debug
      #------------ Kong Plugins -----------------
      #KONG_PLUGINS: bundled,goplug
      KONG_PLUGINS: goplug
      KONG_PLUGINSERVER_NAMES: goplug
      KONG_PLUGINSERVER_GOPLUG_START_CMD: '/usr/local/kong/go-plugins/bin/goplug'
      KONG_PLUGINSERVER_GOPLUG_QUERY_CMD: '/usr/local/kong/go-plugins/bin/goplug -dump'
    command: "kong start"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yaml:/usr/local/kong/config.yaml
      - ./:/usr/local/kong/go-plugins

volumes:
  shared-volume: