ingressController:
  enabled: true
  image:
    repository: kong/nightly-ingress-controller
    tag: nightly
    effectiveSemver: "2.9.0" # <-
  args:
    - --feature-gates=GatewayAlpha=true

image:
  #repository: kong
  repository: kong/kong-gateway
  tag: "3.2"
  # tag: "3.1"
  pullPolicy: Always