receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  otlp:
    endpoint: "https://api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "MY_TEAM_HERE"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
