apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: aatimeout-1
  namespace: kong-mesh-system
  labels:
    kuma.io/origin: zone
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        http:
          requestTimeout: 1s
