apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: timeout-2
  namespace: kong-mesh-system
  labels:
    kuma.io/origin: zone
spec:
  targetRef:
    kind: Mesh
    proxyTypes: [Gateway]
  to:
    - targetRef:
        kind: MeshService
        name: api-play-000_microservice-mesh_svc_8080
      default:
        http:
          requestTimeout: 4s
