# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: <quotes-service> Grant execute permission for gradlew
      run: cd ./quotes-service && chmod +x gradlew
    - name: <quotes-service> Build with Gradle
      run: cd ./quotes-service && ./gradlew build
    - name: <kafka-spring> Grant execute permission for gradlew
      run: cd ./kafka-spring && chmod +x gradlew
    - name: <kafka-spring> Build with Gradle
      run: cd ./kafka-spring && ./gradlew build -x test
    - name: <native-quote-service> Grant execute permission for gradlew
      run: cd ./kong-builders/11-10-2021/native-quote-service && chmod +x gradlew
    - name: <native-quote-service> Build with Gradle
      run: cd ./kong-builders/11-10-2021/native-quote-service && ./gradlew build -x test

